const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 2.5,
      numReviews: 4,
      description: "High quality shirt",
    },
    {
      _id: "2",
      name: "Adidas Fit shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 8,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 300,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality pant",
    },
    {
      _id: "4",
      name: "Adidas Slim Pant",
      slug: "adidas-slim-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 280,
      countInStock: 20,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 7,
      description: "High quality product",
    },
  ],
  users: [
    {
      name: "Pasindu Lakmal",
      email: "pasindu@example.com",
      password: "123@pasindu",
      isAdmin: true,
    },
  ],
};

export default data;
